

package com.usedBooks.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * 
 * @table auction
 * @author Vakoe
 * @date 2019年02月18日 14:06
 */
@Data
@Entity(name="auction")
public class Auction implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     * auction.id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Database Column Remarks:
     *   发布id
     * auction.book_id
     */
    private Integer publishId;


    /**
     * Database Column Remarks:
     *   开始时间
     * auction.begin_time
     */
    private Date beginTime;

    /**
     * Database Column Remarks:
     *   结束时间
     * auction.end_time
     */
    private Date endTime;

    /**
     * auction
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return  java.util.Date  beginTime
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * @param java.util.Date  beginTime
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * @return  java.util.Date  endTime
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    public Date getEndTime() {
        return endTime;
    }

    /**
     * @param java.util.Date  endTime
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}