

package com.usedBooks.pojo;
import lombok.Data;
import javax.persistence.*;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * 
 * @table book
 * @author Vakoe
 * @date 2019年02月18日 14:06
 */

@Entity(name="book")
@Data
public class Book implements Serializable {
    /**
     * Database Column Remarks:
     *   书籍id
     * book.id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Database Column Remarks:
     *   ISBN
     * book.isbn
     */
    private String isbn;

    /**
     * Database Column Remarks:
     *   书籍名称
     * book.name
     */
    private String name;

    /**
     * Database Column Remarks:
     *   作者
     * book.author
     */
    private String author;

    /**
     * Database Column Remarks:
     *   出版社
     * book.publish_house
     */
    private String publishHouse;

    /**
     * Database Column Remarks:
     *   书籍封面图片url
     * book.picture_url
     */
    private String pictureUrl;

    /**
     * Database Column Remarks:
     *   原价
     * book.original_price
     */
    private Double originalPrice;


    /**
     * Database Column Remarks:
     *   分类字典
     * book.classification_id
     */
    private Integer classification;

    private static final long serialVersionUID = 1L;



}