 /*
 * @Project Name:TODO 
 * @File Name:DictionaryData
 * @Package Name:com.usedBooks.pojo
 * @Date:2019年03月07日 21:05
 * @Creator:Vakoe
 * @line------------------------------
 * @修改人:
 * @修改时间:
 * @修改内容:
 */

package com.usedBooks.pojo;

import java.io.Serializable;

 /**
  *
  * This class was generated by MyBatis Generator.
  *
  * @table dictionary_data
  * @author Vakoe
  * @date 2019年03月07日 21:05
  */
 public class DictionaryData implements Serializable {
     /**
      * Database Column Remarks:
      *   id
      * dictionary_data.id
      */
     private Integer id;

     /**
      * Database Column Remarks:
      *   字典值
      * dictionary_data.value
      */
     private String value;

     /**
      * Database Column Remarks:
      *   字典ID
      * dictionary_data.dict_id
      */
     private Integer dictId;

     /**
      * dictionary_data
      */
     private static final long serialVersionUID = 1L;

     /**
      * @return  java.lang.Integer  id
      */
     public Integer getId() {
         return id;
     }

     /**
      * @param java.lang.Integer  id
      */
     public void setId(Integer id) {
         this.id = id;
     }

     /**
      * @return  java.lang.String  value
      */
     public String getValue() {
         return value;
     }

     /**
      * @param java.lang.String  value
      */
     public void setValue(String value) {
         this.value = value;
     }

     /**
      * @return  java.lang.Integer  dictId
      */
     public Integer getDictId() {
         return dictId;
     }

     /**
      * @param java.lang.Integer  dictId
      */
     public void setDictId(Integer dictId) {
         this.dictId = dictId;
     }
 }