 /*
 * @Project Name:TODO 
 * @File Name:DictionaryData
 * @Package Name:com.usedBooks.pojo
 * @Date:2019年03月07日 21:05
 * @Creator:Vakoe
 * @line------------------------------
 * @修改人:
 * @修改时间:
 * @修改内容:
 */

package com.usedBooks.pojo;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.io.Serializable;

 /**
  *
  * This class was generated by MyBatis Generator.
  *
  * @table dictionary_data
  * @author Vakoe
  * @date 2019年03月07日 21:05
  */
 @Data
 @Entity(name="dictionary_data")
 public class DictionaryData implements Serializable {
     /**
      * Database Column Remarks:
      *   id
      * dictionary_data.id
      */
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer id;

     /**
      * Database Column Remarks:
      *   字典值
      * dictionary_data.value
      */
     private String dictValue;

     /**
      * Database Column Remarks:
      *   字典ID
      * dictionary_data.dict_id
      */
     private Integer dictId;


     private String dictKey;


 }