

package com.usedBooks.pojo;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 *
 * @table order_detail
 * @author Vakoe
 * @date 2019年02月18日 14:06
 */
@Entity(name="order_detail")
@Data
public class OrderDetail implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     * order_detail.id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单id
     * order_detail.order_id
     */
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   发布id
     * order_detail.book_id
     */
    private Integer publishId;

    /**
     * Database Column Remarks:
     *   数量
     * order_detail.quantity
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   金额
     * order_detail.totalprice
     */
    private Double totalprice;

    private static final long serialVersionUID = 1L;


}