

package com.usedBooks.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 *
 * @table order_detail
 * @author Vakoe
 * @date 2019年02月18日 14:06
 */
public class OrderDetail implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     * order_detail.id
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   订单id
     * order_detail.order_id
     */
    private Integer orderId;

    /**
     * Database Column Remarks:
     *   书籍id
     * order_detail.book_id
     */
    private Integer bookId;

    /**
     * Database Column Remarks:
     *   数量
     * order_detail.quantity
     */
    private Integer quantity;

    /**
     * Database Column Remarks:
     *   金额
     * order_detail.totalprice
     */
    private Double totalprice;

    /**
     * order_detail
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return  java.lang.Integer  id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param java.lang.Integer  id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return  java.lang.Integer  orderId
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * @param java.lang.Integer  orderId
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * @return  java.lang.Integer  bookId
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * @param java.lang.Integer  bookId
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * @return  java.lang.Integer  quantity
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * @param java.lang.Integer  quantity
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * @return  java.lang.Double  totalprice
     */
    public Double getTotalprice() {
        return totalprice;
    }

    /**
     * @param java.lang.Double  totalprice
     */
    public void setTotalprice(Double totalprice) {
        this.totalprice = totalprice;
    }
}