

package com.usedBooks.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Data;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * 
 * @table order
 * @author Vakoe
 * @date 2019年02月18日 14:06
 */
@Entity(name="order_form")
@Table(name="order_form")
@Data
public class Order implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     * order.id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Database Column Remarks:
     *   买家电话
     * order.buyer_phone
     */
    private String buyerPhone;

    /**
     * Database Column Remarks:
     *   订单编号
     * order.order_number
     */
    private String orderNumber;

    /**
     * Database Column Remarks:
     *   买家用户名
     * order.buyer
     */
    private String buyer;

    /**
     * Database Column Remarks:
     *   买家id
     * order.buyer_id
     */
    private Integer buyerId;

    /**
     * Database Column Remarks:
     *   下单时间
     * order.time
     */
    private Date time;

    /**
     * Database Column Remarks:
     *   订单总金额
     * order.order_amount
     */
    private Double orderAmount;

    /**
     * Database Column Remarks:
     *   实付总金额
     * order.actual_amount
     */
    private Double actualAmount;

    /**
     * Database Column Remarks:
     *   送货方式
     * order.delivery_method
     */
    private String deliveryMethod;

    /**
     * Database Column Remarks:
     *   订单状态  1:未支付，2:已支付，3:待发货，4:已发货
     * order.state
     */
    private Integer state;

    /**
     * Database Column Remarks:
     *   0:没申请取消订单，1：已申请取消订单
     * order.is_cancel
     */
    private Integer isCancel;

    /**
     * Database Column Remarks:
     *   0：订单无效，1：订单有效,0:订单无效
     * order.is_valid
     */
    private Integer isValid;


    /**
     * Database Column Remarks:
     *   卖家用户名
     * order.seller
     */
    private String seller;

    /**
     * Database Column Remarks:
     *   卖家id
     * order.seller_id
     */
    private Integer sellerId;
    /**
     * order_detail
     */

    /**
     * Database Column Remarks:
     *   卖家电话
     * order.seller_phone
     */
    private String sellerPhone;

    /**
     * order
     */
    private static final long serialVersionUID = 1L;


}