
package com.usedBooks.pojo;

import java.io.Serializable;
 /**
  *
  * This class was generated by MyBatis Generator.
  *
  * @table students
  * @author Vakoe
  * @date 2019年02月14日 16:22
  */
 public class Students implements Serializable {
     /**
      * students.id
      */
     private Integer id;

     /**
      * students.name
      */
     private String name;

     /**
      * students.chinese
      */
     private Double chinese;

     /**
      * students.math
      */
     private Double math;

     /**
      * students.english
      */
     private Double english;

     /**
      * students
      */


     /**
      * @return  java.lang.Integer  id
      */
     public Integer getId() {
         return id;
     }

     /**
      * @param java.lang.Integer  id
      */
     public void setId(Integer id) {
         this.id = id;
     }

     /**
      * @return  java.lang.String  name
      */
     public String getName() {
         return name;
     }

     /**
      * @param java.lang.String  name
      */
     public void setName(String name) {
         this.name = name;
     }

     /**
      * @return  java.lang.Double  chinese
      */
     public Double getChinese() {
         return chinese;
     }

     /**
      * @param java.lang.Double  chinese
      */
     public void setChinese(Double chinese) {
         this.chinese = chinese;
     }

     /**
      * @return  java.lang.Double  math
      */
     public Double getMath() {
         return math;
     }

     /**
      * @param java.lang.Double  math
      */
     public void setMath(Double math) {
         this.math = math;
     }

     /**
      * @return  java.lang.Double  english
      */
     public Double getEnglish() {
         return english;
     }

     /**
      * @param java.lang.Double  english
      */
     public void setEnglish(Double english) {
         this.english = english;
     }
 }