 /*
 * @Project Name:TODO 
 * @File Name:User
 * @Package Name:com.usedBooks.pojo
 * @Date:2019年03月03日 11:14
 * @Creator:hengzi
 * @line------------------------------
 * @修改人:
 * @修改时间:
 * @修改内容:
 */

package com.usedBooks.pojo;

import java.io.Serializable;

 /**
  *
  * This class was generated by MyBatis Generator.
  *
  * @table user
  * @author hengzi
  * @date 2019年03月03日 11:14
  */
 public class User implements Serializable {
     /**
      * Database Column Remarks:
      *   主键ID
      * user.id
      */
     private String id;

     /**
      * Database Column Remarks:
      *   用户编号
      * user.user_no
      */
     private String userNo;

     /**
      * Database Column Remarks:
      *   用户名
      * user.user_name
      */
     private String userName;

     /**
      * Database Column Remarks:
      *   电话号码
      * user.phone
      */
     private String phone;

     /**
      * Database Column Remarks:
      *   性别 1：男，2：女
      * user.gender
      */
     private Integer gender;

     /**
      * Database Column Remarks:
      *   密码
      * user.password
      */
     private String password;

     /**
      * Database Column Remarks:
      *   盐值
      * user.salt
      */
     private String salt;

     /**
      * Database Column Remarks:
      *   邮箱
      * user.email
      */
     private String email;

     /**
      * user
      */
     private static final long serialVersionUID = 1L;

     /**
      * @return  java.lang.String  id
      */
     public String getId() {
         return id;
     }

     /**
      * @param java.lang.String  id
      */
     public void setId(String id) {
         this.id = id;
     }

     /**
      * @return  java.lang.String  userNo
      */
     public String getUserNo() {
         return userNo;
     }

     /**
      * @param java.lang.String  userNo
      */
     public void setUserNo(String userNo) {
         this.userNo = userNo;
     }

     /**
      * @return  java.lang.String  userName
      */
     public String getUserName() {
         return userName;
     }

     /**
      * @param java.lang.String  userName
      */
     public void setUserName(String userName) {
         this.userName = userName;
     }

     /**
      * @return  java.lang.String  phone
      */
     public String getPhone() {
         return phone;
     }

     /**
      * @param java.lang.String  phone
      */
     public void setPhone(String phone) {
         this.phone = phone;
     }

     /**
      * @return  java.lang.Integer  gender
      */
     public Integer getGender() {
         return gender;
     }

     /**
      * @param java.lang.Integer  gender
      */
     public void setGender(Integer gender) {
         this.gender = gender;
     }

     /**
      * @return  java.lang.String  password
      */
     public String getPassword() {
         return password;
     }

     /**
      * @param java.lang.String  password
      */
     public void setPassword(String password) {
         this.password = password;
     }

     /**
      * @return  java.lang.String  salt
      */
     public String getSalt() {
         return salt;
     }

     /**
      * @param java.lang.String  salt
      */
     public void setSalt(String salt) {
         this.salt = salt;
     }

     /**
      * @return  java.lang.String  email
      */
     public String getEmail() {
         return email;
     }

     /**
      * @param java.lang.String  email
      */
     public void setEmail(String email) {
         this.email = email;
     }
 }